### ISSUE TITLE
add update checking from GitHub releases.

### ISSUE THREAD

**Issue by portlek** [mfnalex/Spigot-UpdateChecker#7]

**Comment by mfnalex** [comment]
do they have an API?

**Comment by portlek** [comment]
for example
https://api.github.com/repos/portlek/configs
https://api.github.com/repos/portlek/configs/releases/latest

**Comment by mfnalex** [comment]
Thx, will be added soon. If I forget, feel free to create a PR ^^

**Comment by mfnalex** [comment]
I'll add it right now using this https://github.com/hyperdefined/GitHubReleaseAPI :) Sorry for the delay!

**Comment by mfnalex** [comment]
Added in 2.1.0
