### ISSUE TITLE
Allow disabling up-to-date console message

### ISSUE THREAD

**Issue by isiah-lloyd** [mfnalex/Spigot-UpdateChecker#8]
Currently if your plugin is up to date, it logs "[PLUGIN_NAME] You are using the latest version of [PLUGIN_NAME]. I propose an option that allows you to disable this message.

**Comment by mfnalex** [comment]
any idea on how that option could be called? I'm thinking for 30 minutes now but there's nothing I can think of lol

**Comment by isiah-lloyd** [comment]
@mfnalex suppressUpToDateMessage()? Or could be a more general verbose() option that can be used to set other messages down the line?

**Comment by mfnalex** [comment]
suppressUpToDateMessage sounds good!

**Comment by mfnalex** [comment]
added in 1.2.5
